# Generated by Django 5.2.4 on 2025-08-09 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_products_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.customer"
            ),
        ),
    ]
