# Generated by Django 5.2.3 on 2025-07-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_rename_members_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="joined_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="phone",
            field=models.IntegerField(null=True),
        ),
    ]
