# Generated by Django 6.0.1 on 2026-01-26 06:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='file',
            name='is_latest',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(condition=models.Q(('is_latest', True)), fields=('owner', 'project', 'name'), name='one_latest_file_per_logical_file'),
        ),
    ]
