# Generated by Django 5.2.7 on 2025-10-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('crop_type', models.CharField(max_length=200)),
                ('area_has', models.FloatField()),
                ('date_created', models.DateField()),
            ],
        ),
    ]
