# Generated by Django 5.2.4 on 2025-07-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
                ("position", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "msg_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date"),
                ),
                ("comment", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="experience_logos/"
                    ),
                ),
                ("position", models.CharField(blank=True, max_length=200, null=True)),
                ("roles", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "date_joined",
                    models.DateTimeField(blank=True, null=True, verbose_name="Date"),
                ),
                (
                    "date_ended",
                    models.DateTimeField(blank=True, null=True, verbose_name="Date"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="project_image/"
                    ),
                ),
                ("content", models.CharField(max_length=1000)),
                ("tags", models.CharField(max_length=100)),
                ("pub_date", models.DateTimeField(verbose_name="Date Published")),
            ],
        ),
    ]
