# Generated by Django 5.2.4 on 2025-07-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myprofile", "0002_project_name_alter_project_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="img",
        ),
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="project_image/"),
        ),
    ]
