# Generated by Django 5.2.4 on 2025-07-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myprofile", "0003_remove_project_img_project_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="date_ended",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="experience",
            name="date_joined",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date"),
        ),
    ]
