# Generated by Django 5.2.4 on 2025-07-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myprofile", "0004_experience_date_ended_alter_experience_date_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="roles",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
