# Generated by Django 5.2.4 on 2025-07-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myprofile", "0005_experience_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
