# Generated by Django 5.2.4 on 2025-07-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myprofile", "0006_experience_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
